#!/bin/bash
set -o vi
stty -ixon # Disable ctrl-s and ctrl-q.
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/shell/history

[ -f "$HOME/.config/shell/shortcutrc" ] && source "$HOME/.config/shell/shortcutrc" # Load shortcut aliases
[ -f "$HOME/.config/shell/aliasrc" ] && source "$HOME/.config/shell/aliasrc" # Load aliases

# Load options depending on current shell
if [ $(echo $0) = "/bin/zsh" ]; then
	[ -f "$HOME/.config/shell/zspecific" ] && source "$HOME/.config/shell/zspecific"
fi
if [ $(echo $0) = "/bin/bash" ]; then
	[ -f "$HOME/.config/shell/bashspecific" ] && source "$HOME/.config/shell/bashspecific"
fi

pfetch && echo $(vrms) | grep "non-free"
