context.modules = [{
    name = libpipewire-module-loopback
    args = {
        audio.position = [ FL FR ]
        capture.props = {
            media.class = "Audio/Sink"
            node.name = "application-loopback-2-sink"
            node.description = "Application-Loopback 2 Sink"
        }
        playback.props = {
            media.class = "Stream/Output/Audio"
            node.name = "application-loopback-2-playback"
            node.description = "Application-Loopback 2 Playback"
        }
    }
}]
