context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      audio.position = [ FL FR ]
      capture.props = {
        media.class = "Stream/Input/Audio"
        node.name = "device-loopback-3-recording"
        node.description = "Device-Loopback 3 Recording"
      }
      playback.props = {
        media.class = "Stream/Output/Audio"
        node.name = "device-loopback-3-playback"
        node.description = "Device-Loopback 3 Playback"
      }
      audio.volume = 0.5
      audio.mute = true
    }
  }
]
