context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      audio.position = [ FL FR ]

      capture.props = {
        media.class = "Stream/Input/Audio"
        node.name = "virtual-source-1-recording"
        node.description = "Virtual Source 1 Recording"
      }

      playback.props = {
        media.class = "Audio/Source"
        node.name = "virtual-source-1-source"
        node.description = "Virtual Source 1 Source"
      }
    }
  }
]
