#!/bin/sh

# bash
alias ":wq"="exit"
alias ":q"="exit"

# battery
alias "battery"="acpi"

# calcurse
alias cal="calcurse-caldav --init=keep-remote && calcurse"
alias calchange="cd ~/.calcurse/caldav"

# cd
alias ".."="cd .."
alias "..1"="cd .."
alias "..2"="cd ../.."
alias "..3"="cd ../../.."
alias "..4"="cd ../../../.."
alias "..5"="cd ../../../../.."

# cp
alias cp="cp -i"

# clear
alias c="clear && neofetch"

# config
alias config="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

# fzf
sc() { du -a ~/.config/* ~/.local/bin/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
sd() { du -a ~/ownCloud/* | awk '{print $2}' | grep ".pdf" | fzf | xargs -r $READER ;}

# git
alias TexHandout="cp ~/github/Tools/LaTeX\ Templates/LaTeX\ Handout/Handout.tex"

# grep
alias grep="grep --color=auto"

# lastpass
alias lastpass="lpass"

# ls(d)
alias l="lsd"
alias la="lsd -la"
alias ll="lsd -l"
alias tree="lsd --tree"

# mkdir
alias mkdir="mkdir -p"

# mount
alias mount="mount |column -t"

# mv
alias mv="mv -i"

# pacman
alias pac="sudo pacman"
alias pacclean="sudo pacman -Rs $(pacman -Qtdq)"

# ping
alias ping="ping -c 5"

# rm
alias rm="rm -i"

# root/sudo
alias root="sudo -i"
alias su="sudo -i"

# nvim
alias svim="sudo nvim"
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# weather
alias weather="curl wttr.in"


