#!/bin/sh

# bash
alias ":wq"="exit"
alias ":q"="exit"

# cd
alias ".."="cd .."
alias "..."="cd ../.."
alias "...."="cd ../../.."
alias "....."="cd ../../../.."

# cp
alias cp="cp -i"

# clear
alias c="clear"

# config
alias config="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

# fzf
src() { find ~/.config/* ~/.local/bin/* -type f | fzf | xargs -r $EDITOR ;}
srd() { find ~/ownCloud/* -type f | grep ".pdf" | fzf | xargs -r $READER ;}

# git
alias ga="git add"
alias grm="git rm"
alias gc="git commit"
alias gp="git push"

# grep
alias grep="grep --color=auto"

# haste
haste() {
    a=$(cat);
    curl -X POST -s -d "$a" https://paste.tiyn.eu/documents | awk -F '"' '{print "https://paste.tiyn.eu/"$4}';
}

#khal
alias calendar="khal"

# khard
alias contacts="khard"

# ls(d)
alias l="lsd"
alias la="lsd -la"
alias ll="lsd -l"
alias tree="lsd --tree"

# mkdir
alias mkdir="mkdir -p"

# mount
alias mount="mount |column -t"

# mv
alias mv="mv -i"

# pacman
alias pac="sudo pacman"

# ping
alias ping="ping -c 5"

# rm
alias rm="rm -i"

# root/sudo
alias su="sudo -i"
alias sudo="sudo "

#sc-im
alias sc="sc-im"

# script
alias scriptclear="cat typescript | perl -pe 's/\e([^\[\]]|\[.*?[a-zA-Z]|\].*?\a)//g' | col -b > typescript-processed"

# tmux
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"

# nvim
alias svim="sudo nvim"
alias svi="sudo nvim"
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"
command -v nvim >/dev/null && alias vi="nvim" vidiff="nvim -d"

# weather
alias weather="curl wttr.in"

#wget
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
