#!/bin/bash
set -o vi
stty -ixon # Disable ctrl-s and ctrl-q.

[ -f "$HOME/.config/shortcutrc" ] && source "$HOME/.config/shortcutrc" # Load shortcut aliases
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc" # Load aliases

# Load options depending on current shell
if [ $(echo $0) = "/bin/zsh" ]; then
	[ -f "$HOME/.config/zspecific" ] && source "$HOME/.config/zspecific"
fi
if [ $(echo $0) = "/bin/bash" ]; then
	[ -f "$HOME/.config/bashspecific" ] && source "$HOME/.config/bashspecific"
fi

pfetch && echo $(vrms) | grep "non-free"
