#!/bin/sh

xset r rate 300 50 &                    # Speed xrate up
unclutter &                             # Remove mouse when idle
dunst &                                 # dunst for notifications
redshift &                              # redshift for saving your eyes
$STATUSBAR &                            # for refreshing the statusbar
xcompmgr &                              # compositor for transparency
nextcloud &                             # for my cloud
sxhkd &                                 # for shortcuts
easyeffects --gapplication-service &    # load noise suppression for microphone
syncthing &                             # sync data between devices
