#!/bin/sh

xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
dunst &			# dunst for notifications
redshift &		# redshift for saving your eyes
mpd &		# starts the mpd server for music
toggletouchpad & # deactivates the touchpad
$STATUSBAR & # for refreshing the statusbar
owncloud & # for my cloud
sxhkd & # for shortcuts
